### ISSUE TITLE
디렉터리 구조 정하기

### ISSUE THREAD

**Issue by sw1203** [sw1203/SportsInfo#1]
### what
* 디렉터리 구조 정하기
### why
* 서로 협업시 경로가 일치 하지 않으면 추후 코드 실행시 오류가 발생할 수 있음

**Comment by devdeankang** [comment]
#11 
수정된 사항이 직관적으로 바뀌어야 할 파일명이기에 코멘트 남긴 뒤에 이슈 Close합니다.
